services:

  db:
    image: postgres:16-alpine
    container_name: db-obras-teatrais
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: obrasteatrais
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backendteatromanager
      dockerfile: Dockerfile
      
    container_name: backend-teatro-manager
    ports:
      - "5002:5002"
      
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/obrasteatrais
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_FLYWAY_USER=${DB_USER}
      - SPRING_FLYWAY_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
    restart: on-failure 

volumes:
  pgdata: